language: node_js
os: windows
node_js:
  - "stable"
install:
  - npm install
services:
  - postgresql
test:
  adapter: postgresql
  database: ride-my-way
before_script:
  - psql -c 'create database ride-my-way;' -U postgres
  - cp server/config/database.yml.travis config/database.yml
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6
    - postgresql-client-9.6
env:
  global:
  - PGPORT=5433
cache:
  directories:
    - "node_modules"
script:
  - npm test
after_success :
    - npm run coverage
