language: node_js
os: windows 
node_js:
  - "stable"
install:
  - npm install
services:
  - postgresql
before_script:
  - psql -c 'create database ride_my_way;' -U postgres
cache:
  directories:
    - "node_modules"
script:
  - npm test
after_success :
    - npm run coverage
